layout_spectrum: 0.2980588
typography_spectrum: 0.8709677
color:
  saturation: 0.7401434
  brandStrength: 0.4605735
  lightness: 0.6057348
  brandColors:
    - '#8E288E'
    - '#FFFFFF'
    - '#0772B8'
    - '#000000'
    - '#767676'
  rhythmicContrast: 0.3512545
name: Universal Way Martial Arts Academy
